# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Suporte\Desktop\Packs Importantes\Projetos\Copiar-Python\interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(727, 567)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\Suporte\\Desktop\\Packs Importantes\\Projetos\\Copiar-Python\\../Projeto_Copiar/copiar.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 701, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textDirA = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.textDirA.setFont(font)
        self.textDirA.setObjectName("textDirA")
        self.horizontalLayout.addWidget(self.textDirA)
        self.botaoDirA = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.botaoDirA.setObjectName("botaoDirA")
        self.horizontalLayout.addWidget(self.botaoDirA)
        self.caminhoDirA = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.caminhoDirA.setObjectName("caminhoDirA")
        self.horizontalLayout.addWidget(self.caminhoDirA)
        self.horizontalLayout.setStretch(2, 3)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(19, 79, 691, 441))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.horizontalLayoutWidget_2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.listaDirB = QtWidgets.QPlainTextEdit(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.listaDirB.setFont(font)
        self.listaDirB.setReadOnly(True)
        self.listaDirB.setObjectName("listaDirB")
        self.gridLayout.addWidget(self.listaDirB, 1, 1, 1, 1)
        self.listaDirA = QtWidgets.QPlainTextEdit(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.listaDirA.setFont(font)
        self.listaDirA.setReadOnly(True)
        self.listaDirA.setObjectName("listaDirA")
        self.gridLayout.addWidget(self.listaDirA, 1, 0, 1, 1)
        self.textListaDirA = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.textListaDirA.setFont(font)
        self.textListaDirA.setObjectName("textListaDirA")
        self.gridLayout.addWidget(self.textListaDirA, 0, 0, 1, 1)
        self.textListaDirB = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.textListaDirB.setFont(font)
        self.textListaDirB.setObjectName("textListaDirB")
        self.gridLayout.addWidget(self.textListaDirB, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 727, 21))
        self.menubar.setObjectName("menubar")
        self.menuArquivo = QtWidgets.QMenu(self.menubar)
        self.menuArquivo.setObjectName("menuArquivo")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuArquivo.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Projeto Copiar"))
        self.textDirA.setText(_translate("MainWindow", "Caminho Arquivo:"))
        self.botaoDirA.setText(_translate("MainWindow", "Selecionar"))
        self.caminhoDirA.setAccessibleDescription(_translate("MainWindow", "kjkhjk"))
        self.textListaDirA.setText(_translate("MainWindow", "DIRETORIO A"))
        self.textListaDirB.setText(_translate("MainWindow", "DIRETORIO B"))
        self.menuArquivo.setTitle(_translate("MainWindow", "Arquivo"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
