# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Suporte\Desktop\Packs Importantes\Projetos\Copiar-Python\interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(456, 382)
        MainWindow.setMaximumSize(QtCore.QSize(500, 500))
        self.lineEditInserir = QtWidgets.QLineEdit(MainWindow)
        self.lineEditInserir.setGeometry(QtCore.QRect(80, 60, 113, 20))
        self.lineEditInserir.setObjectName("lineEditInserir")
        self.lineEditColar = QtWidgets.QLineEdit(MainWindow)
        self.lineEditColar.setGeometry(QtCore.QRect(80, 120, 113, 20))
        self.lineEditColar.setObjectName("lineEditColar")
        self.pushButtonCopiar = QtWidgets.QPushButton(MainWindow)
        self.pushButtonCopiar.setGeometry(QtCore.QRect(230, 60, 75, 23))
        self.pushButtonCopiar.setObjectName("pushButtonCopiar")
        self.pushButtonColar = QtWidgets.QPushButton(MainWindow)
        self.pushButtonColar.setGeometry(QtCore.QRect(230, 120, 75, 23))
        self.pushButtonColar.setObjectName("pushButtonColar")
        self.pushButtonNovo = QtWidgets.QPushButton(MainWindow)
        self.pushButtonNovo.setGeometry(QtCore.QRect(290, 230, 121, 51))
        self.pushButtonNovo.setObjectName("pushButtonNovo")
        self.textEditLista = QtWidgets.QTextEdit(MainWindow)
        self.textEditLista.setGeometry(QtCore.QRect(30, 160, 241, 211))
        self.textEditLista.setObjectName("textEditLista")

        self.retranslateUi(MainWindow)
        self.pushButtonCopiar.pressed.connect(self.lineEditInserir.selectAll) # type: ignore
        self.pushButtonCopiar.released.connect(self.lineEditInserir.copy) # type: ignore
        self.pushButtonColar.clicked.connect(self.lineEditColar.paste) # type: ignore
        self.pushButtonNovo.clicked.connect(self.textEditLista.paste) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Hello World PyQt"))
        self.pushButtonCopiar.setText(_translate("MainWindow", "COPIAR"))
        self.pushButtonColar.setText(_translate("MainWindow", "COLAR"))
        self.pushButtonNovo.setText(_translate("MainWindow", "Novo Botão"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QWidget()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
